apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: hello-world
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
